In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("index.csv")

In [3]:
df.head()

Creditability  Account Balance  Duration of Credit (month)  \
0              1                1                          18   
1              1                1                           9   
2              1                2                          12   
3              1                1                          12   
4              1                1                          12   

   Payment Status of Previous Credit  Purpose  Credit Amount  \
0                                  4        2           1049   
1                                  4        0           2799   
2                                  2        9            841   
3                                  4        0           2122   
4                                  4        0           2171   

   Value Savings/Stocks  Length of current employment  Instalment per cent  \
0                     1                             2                    4   
1                     1                             3                    2   
2                     2                             4                    2   
3                     1                             3                    3   
4                     1                             3                    4   

   Sex & Marital Status  ...  Duration in Current address  \
0                     2  ...                            4   
1                     3  ...                            2   
2                     2  ...                            4   
3                     3  ...                            2   
4                     3  ...                            4   

   Most valuable available asset  Age (years)  Concurrent Credits  \
0                              2           21                   3   
1                              1           36                   3   
2                              1           23                   3   
3                              1           39                   3   
4                              2           38                   1   

   Type of apartment  No of Credits at this Bank  Occupation  \
0                  1                           1           3   
1                  1                           2           3   
2                  1                           1           2   
3                  1                           2           2   
4                  2                           2           2   

   No of dependents  Telephone  Foreign Worker  
0                 1          1               1  
1                 2          1               1  
2                 1          1               1  
3                 2          1               2  
4                 1          1               2  

[5 rows x 21 columns]

In [4]:
X = df.drop(columns = ["Creditability"])
y = df['Creditability']

In [5]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
sc = StandardScaler()

In [8]:
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
X_test

array([[ 1.1387847 ,  1.21250495, -0.49306245, ..., -0.41144194,
         1.15168958, -0.17988183],
       [ 1.1387847 , -0.26948651,  1.37861936, ..., -0.41144194,
        -0.86828953, -0.17988183],
       [ 1.1387847 , -0.76348366, -0.49306245, ..., -0.41144194,
        -0.86828953, -0.17988183],
       ...,
       [ 1.1387847 , -0.76348366,  1.37861936, ..., -0.41144194,
        -0.86828953, -0.17988183],
       [-1.25302016,  1.7065021 ,  1.37861936, ..., -0.41144194,
        -0.86828953, -0.17988183],
       [ 1.1387847 , -0.26948651, -0.49306245, ..., -0.41144194,
        -0.86828953, -0.17988183]])

In [10]:
y_train = y_train.to_numpy()

In [11]:
y_train

array([1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0,

In [12]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [13]:
from tensorflow.keras.optimizers import Adamax, Adam, RMSprop, SGD

In [14]:
# Dense -> adding Hidden input layers
ann_variable = tf.keras.models.Sequential()

ann_variable.add(tf.keras.layers.Dense(units=8,activation='relu'))

ann_variable.add(tf.keras.layers.Dense(units=8,activation='relu'))

ann_variable.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

ann_variable.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [15]:
ann_variable.fit(X_train,y_train,batch_size=32,epochs=50)

Train on 670 samples
Epoch 1/50
670/670 [==============================] - 1s 2ms/sample - loss: 0.6841 - accuracy: 0.5657
Epoch 2/50
670/670 [==============================] - 0s 64us/sample - loss: 0.6664 - accuracy: 0.6164
Epoch 3/50
670/670 [==============================] - 0s 56us/sample - loss: 0.6535 - accuracy: 0.6582
Epoch 4/50
670/670 [==============================] - 0s 61us/sample - loss: 0.6425 - accuracy: 0.6746
Epoch 5/50
670/670 [==============================] - 0s 58us/sample - loss: 0.6325 - accuracy: 0.6896
Epoch 6/50
670/670 [==============================] - 0s 58us/sample - loss: 0.6237 - accuracy: 0.6985
Epoch 7/50
670/670 [==============================] - 0s 57us/sample - loss: 0.6155 - accuracy: 0.7000
Epoch 8/50
670/670 [==============================] - 0s 52us/sample - loss: 0.6080 - accuracy: 0.7015
Epoch 9/50
670/670 [==============================] - 0s 49us/sample - loss: 0.6003 - accuracy: 0.7030
Epoch 10/50
670/670 [==============================] 

In [16]:
Y_pred = ann_variable.predict(X_test)
Y_pred

array([[0.35518122],
       [0.96236587],
       [0.9311018 ],
       [0.99311256],
       [0.9399007 ],
       [0.8710433 ],
       [0.92900383],
       [0.4843231 ],
       [0.22285789],
       [0.91060007],
       [0.05954105],
       [0.9638953 ],
       [0.9107996 ],
       [0.15098995],
       [0.3290431 ],
       [0.9719385 ],
       [0.6556672 ],
       [0.669933  ],
       [0.17318785],
       [0.9927279 ],
       [0.9919721 ],
       [0.84886575],
       [0.9693841 ],
       [0.5998124 ],
       [0.9989485 ],
       [0.17152789],
       [0.12269557],
       [0.97647756],
       [0.7306762 ],
       [0.74674356],
       [0.96140695],
       [0.96485853],
       [0.58839786],
       [0.7440926 ],
       [0.24703193],
       [0.9461075 ],
       [0.6443634 ],
       [0.5776882 ],
       [0.45703894],
       [0.8882408 ],
       [0.999154  ],
       [0.8765788 ],
       [0.89846194],
       [0.15466404],
       [0.8639815 ],
       [0.75626844],
       [0.47093078],
       [0.946

In [17]:
Y_pred = (Y_pred > 0.5)

In [18]:
Y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [19]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [20]:
confusion_matrix(Y_pred,y_test)

array([[ 46,  27],
       [ 52, 205]])

In [21]:
cm_ANN = confusion_matrix(y_test, Y_pred)

In [22]:
tn, fp, fn, tp = cm_ANN.ravel()

In [23]:
precision_ann = precision_score(y_test, Y_pred)
print("precision = "+str(precision_ann))
recall_ann = recall_score(y_test, Y_pred)
print("recall = "+ str(recall_ann))
accuracy_ann = accuracy_score(y_test, Y_pred)
print("accuracy = "+ str(accuracy_ann))
F1_score_ann = f1_score(y_test, Y_pred)
print("F1 Score = "+ str(F1_score_ann))

precision = 0.7976653696498055
recall = 0.8836206896551724
accuracy = 0.7606060606060606
F1 Score = 0.8384458077709612


In [24]:
specificity = (tn)/(tn+fp)
print("specificity ="+ str(specificity))

specificity =0.46938775510204084


In [40]:
# Dense -> adding Hidden input layers
ann_variable = tf.keras.models.Sequential()

ann_variable.add(tf.keras.layers.Dense(units=8,activation='sigmoid'))

ann_variable.add(tf.keras.layers.Dense(units=8,activation='sigmoid'))

ann_variable.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

ann_variable.compile(optimizer=Adam(lr=0.02),loss='binary_crossentropy',metrics=['accuracy'])

In [41]:
ann_variable.fit(X_train,y_train,batch_size=32,epochs=10)

Train on 670 samples
Epoch 1/10
670/670 [==============================] - 1s 1ms/sample - loss: 0.6014 - accuracy: 0.6985
Epoch 2/10
670/670 [==============================] - 0s 51us/sample - loss: 0.5453 - accuracy: 0.7000
Epoch 3/10
670/670 [==============================] - 0s 46us/sample - loss: 0.4978 - accuracy: 0.7612
Epoch 4/10
670/670 [==============================] - 0s 45us/sample - loss: 0.4883 - accuracy: 0.7687
Epoch 5/10
670/670 [==============================] - 0s 49us/sample - loss: 0.4811 - accuracy: 0.7731
Epoch 6/10
670/670 [==============================] - 0s 46us/sample - loss: 0.4773 - accuracy: 0.7776
Epoch 7/10
670/670 [==============================] - 0s 50us/sample - loss: 0.4709 - accuracy: 0.7761
Epoch 8/10
670/670 [==============================] - 0s 47us/sample - loss: 0.4699 - accuracy: 0.7851
Epoch 9/10
670/670 [==============================] - 0s 49us/sample - loss: 0.4653 - accuracy: 0.7776
Epoch 10/10
670/670 [==============================] 

In [42]:
Y_pred = ann_variable.predict(X_test)
Y_pred

array([[0.30660394],
       [0.9543202 ],
       [0.8791518 ],
       [0.92050904],
       [0.94145036],
       [0.9279741 ],
       [0.91048837],
       [0.40174866],
       [0.59944236],
       [0.9500338 ],
       [0.26022547],
       [0.9585932 ],
       [0.86427987],
       [0.26014018],
       [0.3574407 ],
       [0.9350499 ],
       [0.90918636],
       [0.57011986],
       [0.29569364],
       [0.95618284],
       [0.9584129 ],
       [0.928647  ],
       [0.9571096 ],
       [0.6621382 ],
       [0.96144986],
       [0.34838763],
       [0.38897857],
       [0.9541191 ],
       [0.6803406 ],
       [0.7576767 ],
       [0.9528004 ],
       [0.9467005 ],
       [0.8518732 ],
       [0.76724136],
       [0.36329156],
       [0.9072416 ],
       [0.40079626],
       [0.46386045],
       [0.47138458],
       [0.8734394 ],
       [0.9611722 ],
       [0.896001  ],
       [0.9581369 ],
       [0.4197406 ],
       [0.9089953 ],
       [0.8351377 ],
       [0.3588888 ],
       [0.945

In [43]:
Y_pred = (Y_pred > 0.5)

In [44]:
Y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [

In [45]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [46]:
confusion_matrix(Y_pred,y_test)

array([[ 48,  29],
       [ 50, 203]])

In [47]:
cm_ANN = confusion_matrix(y_test, Y_pred)

In [48]:
tn, fp, fn, tp = cm_ANN.ravel()

In [49]:
precision_ann = precision_score(y_test, Y_pred)
print("precision = "+str(precision_ann))
recall_ann = recall_score(y_test, Y_pred)
print("recall = "+ str(recall_ann))
accuracy_ann = accuracy_score(y_test, Y_pred)
print("accuracy = "+ str(accuracy_ann))
F1_score_ann = f1_score(y_test, Y_pred)
print("F1 Score = "+ str(F1_score_ann))

precision = 0.8023715415019763
recall = 0.875
accuracy = 0.7606060606060606
F1 Score = 0.8371134020618557


In [50]:
specificity = (tn)/(tn+fp)
print("specificity ="+ str(specificity))

specificity =0.4897959183673469


In [72]:
# Dense -> adding Hidden input layers
ann_variable = tf.keras.models.Sequential()

ann_variable.add(tf.keras.layers.Dense(units=8,activation='sigmoid'))

ann_variable.add(tf.keras.layers.Dense(units=8,activation='sigmoid'))

ann_variable.add(tf.keras.layers.Dense(units=1,activation='relu'))

ann_variable.compile(optimizer= SGD(lr=0.0002,momentum=0.02),loss='binary_crossentropy',metrics=['accuracy'])

In [73]:
ann_variable.fit(X_train,y_train,batch_size=32,epochs=20)

Train on 670 samples
Epoch 1/20
670/670 [==============================] - 1s 757us/sample - loss: 1.2986 - accuracy: 0.3015
Epoch 2/20
670/670 [==============================] - 0s 47us/sample - loss: 1.1410 - accuracy: 0.3015
Epoch 3/20
670/670 [==============================] - 0s 50us/sample - loss: 1.0471 - accuracy: 0.3015
Epoch 4/20
670/670 [==============================] - 0s 48us/sample - loss: 0.9804 - accuracy: 0.3015
Epoch 5/20
670/670 [==============================] - 0s 47us/sample - loss: 0.9294 - accuracy: 0.3015
Epoch 6/20
670/670 [==============================] - 0s 49us/sample - loss: 0.8884 - accuracy: 0.3015
Epoch 7/20
670/670 [==============================] - 0s 46us/sample - loss: 0.8547 - accuracy: 0.3015
Epoch 8/20
670/670 [==============================] - 0s 46us/sample - loss: 0.8263 - accuracy: 0.3030
Epoch 9/20
670/670 [==============================] - 0s 49us/sample - loss: 0.8021 - accuracy: 0.3090
Epoch 10/20
670/670 [==============================

In [74]:
Y_pred = ann_variable.predict(X_test)
Y_pred

array([[0.515286  ],
       [0.5745107 ],
       [0.4583881 ],
       [0.6264532 ],
       [0.51974607],
       [0.5478907 ],
       [0.57678765],
       [0.54228467],
       [0.58018523],
       [0.57327044],
       [0.5234548 ],
       [0.54125583],
       [0.58940053],
       [0.46831667],
       [0.50391984],
       [0.5063458 ],
       [0.51315314],
       [0.50884795],
       [0.62959   ],
       [0.63355595],
       [0.505968  ],
       [0.56797147],
       [0.53903544],
       [0.4898954 ],
       [0.6050361 ],
       [0.5603368 ],
       [0.44627976],
       [0.5809837 ],
       [0.61072993],
       [0.5798106 ],
       [0.5816241 ],
       [0.54775476],
       [0.55115265],
       [0.5707648 ],
       [0.49205226],
       [0.5749169 ],
       [0.46752137],
       [0.6138956 ],
       [0.5809079 ],
       [0.5163573 ],
       [0.63131803],
       [0.47606802],
       [0.50114775],
       [0.47935855],
       [0.54674584],
       [0.49126738],
       [0.5188775 ],
       [0.511

In [75]:
Y_pred = (Y_pred > 0.5)

In [76]:
#Y_pred

In [77]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [78]:
confusion_matrix(Y_pred,y_test)

array([[ 34,  49],
       [ 64, 183]])

In [79]:
cm_ANN = confusion_matrix(y_test, Y_pred)

In [80]:
tn, fp, fn, tp = cm_ANN.ravel()

In [81]:
precision_ann = precision_score(y_test, Y_pred)
print("precision = "+str(precision_ann))
recall_ann = recall_score(y_test, Y_pred)
print("recall = "+ str(recall_ann))
accuracy_ann = accuracy_score(y_test, Y_pred)
print("accuracy = "+ str(accuracy_ann))
F1_score_ann = f1_score(y_test, Y_pred)
print("F1 Score = "+ str(F1_score_ann))

precision = 0.7408906882591093
recall = 0.7887931034482759
accuracy = 0.6575757575757576
F1 Score = 0.7640918580375783


In [82]:
specificity = (tn)/(tn+fp)
print("specificity ="+ str(specificity))

specificity =0.3469387755102041


In [97]:
# Dense -> adding Hidden input layers
ann_variable = tf.keras.models.Sequential()

ann_variable.add(tf.keras.layers.Dense(units=8,activation='tanh'))

ann_variable.add(tf.keras.layers.Dense(units=8,activation='sigmoid'))

ann_variable.add(tf.keras.layers.Dense(units=1,activation='tanh'))

ann_variable.compile(optimizer= RMSprop(lr=0.02),loss='binary_crossentropy',metrics=['accuracy'])

In [98]:
ann_variable.fit(X_train,y_train,batch_size=32,epochs=25)

Train on 670 samples
Epoch 1/25
670/670 [==============================] - 1s 978us/sample - loss: 0.5722 - accuracy: 0.6836
Epoch 2/25
670/670 [==============================] - 0s 47us/sample - loss: 0.5068 - accuracy: 0.7597
Epoch 3/25
670/670 [==============================] - 0s 47us/sample - loss: 0.4890 - accuracy: 0.7806
Epoch 4/25
670/670 [==============================] - 0s 48us/sample - loss: 0.4807 - accuracy: 0.7701
Epoch 5/25
670/670 [==============================] - 0s 48us/sample - loss: 0.4630 - accuracy: 0.7716
Epoch 6/25
670/670 [==============================] - 0s 49us/sample - loss: 0.4473 - accuracy: 0.7836
Epoch 7/25
670/670 [==============================] - 0s 48us/sample - loss: 0.4522 - accuracy: 0.7776
Epoch 8/25
670/670 [==============================] - 0s 52us/sample - loss: 0.4214 - accuracy: 0.8000
Epoch 9/25
670/670 [==============================] - 0s 48us/sample - loss: 0.4328 - accuracy: 0.7866
Epoch 10/25
670/670 [==============================

In [99]:
Y_pred = ann_variable.predict(X_test)
Y_pred

array([[ 0.03089861],
       [ 0.99200696],
       [ 0.89585966],
       [ 0.9962569 ],
       [ 0.9961814 ],
       [ 0.98045146],
       [ 0.55937916],
       [ 0.5454598 ],
       [-0.19727512],
       [ 0.97952545],
       [-0.90055543],
       [ 0.99766606],
       [ 0.7432627 ],
       [-0.2590682 ],
       [-0.36655304],
       [ 0.948889  ],
       [ 0.9426671 ],
       [ 0.6855714 ],
       [-0.6253078 ],
       [ 0.9373934 ],
       [ 0.99847555],
       [ 0.48331875],
       [ 0.99287724],
       [ 0.39058807],
       [ 0.9950928 ],
       [-0.8414468 ],
       [ 0.81797546],
       [ 0.95979565],
       [ 0.8211399 ],
       [-0.08709154],
       [ 0.9934448 ],
       [ 0.95693314],
       [ 0.5391115 ],
       [ 0.8430262 ],
       [ 0.6320487 ],
       [ 0.8123435 ],
       [ 0.05357563],
       [ 0.36305124],
       [ 0.5541301 ],
       [ 0.86096936],
       [ 0.9983863 ],
       [ 0.78137136],
       [ 0.9873119 ],
       [ 0.80198354],
       [ 0.79409   ],
       [ 0

In [100]:
Y_pred = (Y_pred > 0.5)

In [101]:
Y_pred

array([[False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [ True],
       [

In [102]:
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.metrics import precision_score, recall_score, f1_score, accuracy_score

In [103]:
confusion_matrix(Y_pred,y_test)

array([[ 51,  37],
       [ 47, 195]])

In [104]:
cm_ANN = confusion_matrix(y_test, Y_pred)

In [105]:
tn, fp, fn, tp = cm_ANN.ravel()

In [106]:
precision_ann = precision_score(y_test, Y_pred)
print("precision = "+str(precision_ann))
recall_ann = recall_score(y_test, Y_pred)
print("recall = "+ str(recall_ann))
accuracy_ann = accuracy_score(y_test, Y_pred)
print("accuracy = "+ str(accuracy_ann))
F1_score_ann = f1_score(y_test, Y_pred)
print("F1 Score = "+ str(F1_score_ann))

precision = 0.8057851239669421
recall = 0.8405172413793104
accuracy = 0.7454545454545455
F1 Score = 0.8227848101265822


In [107]:
specificity = (tn)/(tn+fp)
print("specificity ="+ str(specificity))

specificity =0.5204081632653061
